/* This is stub file for gapi.client.firestore definition tests */
/* IMPORTANT.
 * This file was automatically generated by https://github.com/Maxim-Mazurok/google-api-typings-generator. Please do not edit it manually.
 * In case of any problems please post issue to https://github.com/Maxim-Mazurok/google-api-typings-generator
 **/
gapi.load('client', () => {
  // eslint-disable-next-line @typescript-eslint/no-empty-function
  async function run(): Promise<any> {}

  /** now we can use gapi.client */
  gapi.client.load('firestore', 'v1', () => {
    /** now we can use gapi.client.firestore */

    /** don't forget to authenticate your client before sending any request to resources: */
    /** declare client_id registered in Google Developers Console */
    const client_id = '<<PUT YOUR CLIENT ID HERE>>';
    const scope = [
      /** View and manage your data across Google Cloud Platform services */
      'https://www.googleapis.com/auth/cloud-platform',
      /** View and manage your Google Cloud Datastore data */
      'https://www.googleapis.com/auth/datastore',
    ];
    const immediate = false;
    gapi.auth.authorize({ client_id, scope, immediate }, (authResult) => {
      if (authResult && !authResult.error) {
        /** handle successful authorization */
        run();
      } else {
        /** handle authorization error */
      }
    });
  });
});
